site_name: DraftKings Client
site_url: https://jaebadley.github.io/draftkings_client
site_author: Jae Bradley
repo_name: jaebradley/draftkings_client
repo_url: https://github.com/jaebradley/draftkings_client
nav:
  - Home: index.md
  - API: api.md
  - Development: development.md
theme: material
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.magiclink
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.superfences
  - toc:
      permalink: true
